apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yobot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/nouranha/team7_1'
    targetRevision: HEAD
    path: 'k8s'
  project: default
